name: Publish to PyPI
run-name: Publish Python Package to PyPI for release ${{ github.event.release.tag_name || inputs.tag_name || github.ref_name }}

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Git tag to checkout and publish"
        required: false
        type: string

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name || github.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  publish-to-pypi:
    name: Publish to PyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/nshmdb

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  post-publish:
    name: Post-Publish build database
    needs: [publish-to-pypi]
    runs-on: ubuntu-latest
    env:
      NSHMDB_VERSION: ${{ github.event.release.tag_name || inputs.tag_name || github.ref_name }}
      NSHM_VERSION: 1.0.4

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install the package
        run: pip install nshmdb==${{ env.NSHMDB_VERSION }}

      - name: Generate Database
        run: |
          nshmdb ${{ env.NSHM_VERSION }} nshmdb.db
        env:
          NSHMDB_API_KEY: ${{ secrets.NSHMDB_API_KEY }}

      - name: Setup rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Sync database to Dropbox
        run: |
          rclone copy nshmdb.db 'dropbox:/QuakeCoRE/Public/NSHM/nshmdb_${{ env.NSHMDB_VERSION }}.db'
